definitions:
  assignment001.echoResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /echo:
    get:
      description: Sending a get request to the echo endpoint should always return
        a response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/assignment001.echoResponse'
      summary: Uptime endpoint
      tags:
      - Global
  /v1.0/twitter/{id}:
    get:
      description: Handles getting a special twitt
      parameters:
      - description: a valid twitt id value
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: ""
      security:
      - Bearer: []
      summary: get twitt
      tags:
      - V1 Twitter
swagger: "2.0"
